### ISSUE TITLE
Non-GitHub-Integrated KB Articles still show GitHub Integration-related links on frontend

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#100]
When a KB Article is created inside WordPress (instead of using the GitHub Integration to create a GitHub issue and Markdown file), the KB Article still shows the links to "improve this article" (links to the associated GitHub Issue) and the "[edit]" link (which links to the associated Markdown file).

However, when a KB Article is created inside WordPress instead of using the GitHub Integration, there is no GitHub Issue or Markdown file associated with it, so both of these links lead nowhere useful (well, at least the "edit" link leads nowhere useful; you could argue that linking to the KB Article GitHub repo `/issues/` is still somewhat useful, as someone could just create a new GitHub Issue to suggest improvements, but I'd say that's not the intended behavior here).

Both of these links should be removed when a KB Article is created inside WordPress instead of through the GitHub Integration.

Example: http://s2member.com/kb-article/can-i-customize-pro-forms/

![2015-03-25_22-39-00](https://cloud.githubusercontent.com/assets/53005/6839533/476509e6-d340-11e4-988d-77e7896d2672.png)

---

## What Actions Need To Occur Here?

- [ ] Fix bug in [this template file](https://github.com/websharks/wp-kb-articles-pro/blob/000000-dev/wp-kb-articles-pro/includes/templates/type-a/site/articles/footer.php#L37) and in [this template file](https://github.com/websharks/wp-kb-articles-pro/blob/000000-dev/wp-kb-articles-pro/includes/templates/type-s/site/articles/snippet/footer.php#L13) that incorrectly link to the MD file on GitHub. Instead, this link should lead to the KB Article within WordPress, where the article can be edited within the WP Dashboard. When linking to the WordPress Dashboard instead of GitHub, the GitHub Icon should not appear.
- [ ] The link that reads "how can we improve" should lead to the New Issue form in the underlying GitHub repo instead of the full list of Issues, which is a little confusing for an end-user.

**Comment by jaswsinc** [comment]
Adding a list of actions (↑ above) that need to occur.

**Comment by raamdev** [comment]
Updating next action list to include the following note regarding the [edit] link: "When linking to the WordPress Dashboard instead of GitHub, the GitHub Icon should not appear."

**Comment by jaswsinc** [comment]
Ah, thanks!

**Comment by jaswsinc** [comment]
This has been resolved. s2Member.com and ZenCache.com updated.

**Comment by raamdev** [comment]
Tested and confirmed fixed. Thank you! :-)
