### ISSUE TITLE
README.md files are processed up by GitHub Processor

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#102]
When I created a `README.md` file as a placeholder [here](https://github.com/websharks/zencache-kb/tree/master/features), the WP KB Articles GitHub Integration picked up the file and processed it like a KB Article:

![2015-04-04_17-37-40](https://cloud.githubusercontent.com/assets/53005/6994696/78c6bee0-daf1-11e4-85f9-2bd385ecb073.png)

I would expect WP KB Articles to ignore any Markdown files with a filename `README*`

**Comment by jaswsinc** [comment]
Thanks for the report.
I noticed this at s2Member.com also.

The current list of excluded file names is [here](https://github.com/websharks/wp-kb-articles-pro/blob/000000-dev/wp-kb-articles-pro/includes/classes/github-api.php#L93). It looks like the new GitHub event handler is circumventing this though, and it is allowing push events on README files (and others) to be mirrored on the WP side.

**Comment by jaswsinc** [comment]
This has been resolved. s2Member.com and ZenCache.com updated.

**Comment by raamdev** [comment]
Thank you! :-)
