### ISSUE TITLE
Show "Last Updated" date on KB Articles

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#108]
The KB Articles currently show the published date at the bottom (in the Author Card). It would be nice to also show the "Last Updated" date, so people can see how recently the article has been updated.

![2015-05-22_19-50-11](https://cloud.githubusercontent.com/assets/53005/7781395/ce414d50-00bb-11e5-8fc1-888b6cf89c25.png)

Suggested in https://github.com/websharks/s2member/issues/558.

---

## Next Actions

- [ ] Update [this template file](https://github.com/websharks/wp-kb-articles/blob/000000-dev/wp-kb-articles/includes/templates/type-a/site/articles/footer.php)

**Comment by jaswsinc** [comment]
Agree. Marking this as ready for work and adding Next Actions above.

**Comment by jaswsinc** [comment]
This has been implemented. Coming in an update soon.

![2015-06-07_17-20-56](https://cloud.githubusercontent.com/assets/1563559/8026980/b9ac1296-0d39-11e5-8679-89ce1971afa3.png)
