### ISSUE TITLE
Add "Recently Published" tab to KB Articles List and set as default view

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#110]
_This feature request was originally suggested by @bridgeport in https://github.com/websharks/s2member/issues/558_.

We should be able to see a list of the newest KB Articles, sorted newest to oldest, and that list should be the default view when visiting the KB. I think a new tab called "Recently Published" that is selected by default when someone visits the KB would make the most sense. (On the same note, I've always felt it looked odd that no tab was selected by default when you visit the KB--it leaves you wondering, "where am I right now? what view am I looking at?"). 

The words "Recently Published" also add to the feeling that the KB is constantly changing:

![2015-05-22_20-07-42](https://cloud.githubusercontent.com/assets/53005/7781562/4fcee088-00be-11e5-9f5b-f893e3b283db.png)

**Comment by jaswsinc** [comment]
Agree! :+1:

**Comment by jaswsinc** [comment]
This has been implemented. Coming in an update soon.

**Comment by jaswsinc** [comment]
![2015-06-07_18-34-09](https://cloud.githubusercontent.com/assets/1563559/8027391/d1c880f8-0d43-11e5-8f16-e3aae35a67c0.png)
