### ISSUE TITLE
WordPress Custom Post Type Feeds

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#26]
It would be nice to produce feeds for KB articles also.
https://www.google.com/search?q=wordpress%20custom%20post%20type%20feeds

**Comment by raamdev** [comment]
Oh yes! I second this. KB article feeds would be fantastic.

**Comment by jaswsinc** [comment]
I see this is already possible in WordPress.

### Here are some examples we can go by:

http://zencache.com/feed/?post_type=kb_article
http://zencache.com/feed/?post_type=kb_article&kb_article_category=questions
http://zencache.com/feed/?post_type=kb_article&kb_article_tag=quick-cache
http://zencache.com/kb-article/questions-8-what-are-u-directories/feed/

**Comment by raamdev** [comment]
> I see this is already possible in WordPress.

Doh! I knew that......
