### ISSUE TITLE
Popularity Button Text "Show the author..."

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#27]
I recommend changing this to "Let the author know by clicking here!" ('show' feels like the wrong word):

![2015-01-13_18-28-37](https://cloud.githubusercontent.com/assets/53005/5731514/4425681e-9b52-11e4-8a1b-42a5063b95d8.png)

**Comment by jaswsinc** [comment]
Changed. Thank you.

**Comment by raamdev** [comment]
Awesome. Thank you!
