### ISSUE TITLE
A link for "How can we improve this article?"

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#30]
It would be great if there was a link somewhere on each KB article that allowed visitors a way of providing feedback. For example, if someone discovers that a KB article is now out-of-date (a feature changed, or options were moved around after a software upgrade, for example) it would be nice to have _some_ way of allowing them to provide such feedback.

When WP KB Articles is setup with the GitHub Integration, the plugin should check if there's a YAML data key called `github-issue`, whose value would contain a link to the GitHub Issue associated with that KB article.

```
---
github-issue: https://github.com/websharks/zencache-kb/issues/9
---
```

That could then be used when creating the "How can we improve this article?" link on the associated KB article.

When the GitHub Integration is active and no `github-issue` key exists for a given KB article, the default could be to simply link to the repo's Issues section. 

(Note: I would avoid linking directly to `/issues/new` because the user may not be logged in; linking to `/issues/` would at least let a non-logged in user view the list of Issues to get a feel for how we're tracking feedback, instead of being redirected to a login page.)

---

For non-GitHub Integrations, the "How can we improve this article?" link could simply be configured by the site owner to link to an email address or to a contact form. The WP KB Articles plugin options could have a new field for this link that accepts `mailto:feedback@example.com` or `http://example.com/feedback/` style links.

**Comment by jaswsinc** [comment]
Love the idea!

**Comment by jaswsinc** [comment]
@raamdev Would you mind posting a mockup that shows where you'd like to see this link appear in the article. Maybe just a screenshot of a KB article at ZenCache.com with the link on top of that in the place where you imagine it going.

"How can we improve this article?"

**Comment by raamdev** [comment]
> a mockup that shows where you'd like to see this link appear

![2015-01-17_14-02-59](https://cloud.githubusercontent.com/assets/53005/5789979/94912dfe-9e51-11e4-86f7-3620c49cd6df.png)

**Comment by raamdev** [comment]
Another idea: Get rid of "Tagged" at the bottom (it's already at the top) and replace it with the question, possibly with a nice "editing" type icon before the question:

![2015-01-17_14-06-44](https://cloud.githubusercontent.com/assets/53005/5789991/2995b276-9e52-11e4-8109-2e636f89be57.png)

Putting it there also works because it's right above the author of the article, so it feels more like the author asking how the article can be improved, whereas putting it above the heart makes it feel like "we want you to heart this, so we're also asking how we can improve it, just to be on your good side". Haha.

**Comment by raamdev** [comment]
The latter option will also leave more room for supplying your own question, in case the site owner wants to use a different wording that is a bit longer. Putting it in place of "Tagged" will also make reformatting for mobile display easier than having two separate sentences on the same line ("Tagged:" and "How can we improve this article?").

**Comment by raamdev** [comment]
Woohoo! I love it! Thank you! 

![2015-01-17_18-50-58](https://cloud.githubusercontent.com/assets/53005/5790838/d6226404-9e79-11e4-805c-36138c15f224.png)

**Comment by jaswsinc** [comment]
Great! :-) Welcome.

I updated the article here regarding the YAML config. fields and the formats accepted in the `github-issue:` field. https://github.com/websharks/wp-kb-articles/wiki/YAML-Front-Matter-for-GitHub-Integration
