### ISSUE TITLE
Markdown Blockquote syntax gets converted to HTML Entity

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#31]
If I create a Markdown file on the GitHub repo with the following:

```
> I see in my cache directory sub-directories that end in `.u`, such as `/category.u/`; what are those?
```

When WP KB Articles pulls it into WordPress, the `>` gets converted to `&gt;`:

```
&gt; I see in my cache directory sub-directories that end in `.u`, such as `/category.u/`; what are those?
```

This results in the `>` character showing up on the live site, instead of the expected Blockquote:

![2015-01-15_20-18-14](https://cloud.githubusercontent.com/assets/53005/5770102/aca0f262-9cf3-11e4-8387-aba8a9224303.png)

**Comment by raamdev** [comment]
Referencing the Markdown file where I discovered this: https://github.com/websharks/zencache-kb/blob/master/questions/8-what-are-u-directories.md

**Comment by jaswsinc** [comment]
I corrected two issues that I found while researching this. However, I was unable to actually reproduce the mirror from GitHub to WordPress where `>` becomes `&gt;`. The only way I was able to reproduce this was to publish the KB article in WordPress while on the Visual tab.

Is it possible that you did this? If so, this could be something to watch out for. I don't see an easy to avoid this problem if the post is written in Markdown or raw HTML and the Visual editor is used. I'll leave this open until I hear back :-)

**Comment by raamdev** [comment]
> The only way I was able to reproduce this was to publish the KB article in WordPress while on the Visual tab. Is it possible that you did this?

No, not possible. :) However, what I did do was copy the raw Markdown from a GitHub Issue and pasted it into the new file (when creating it via the GitHub web interface). That's all I did.

**Comment by raamdev** [comment]
Here's the video of how I created this file: https://www.youtube.com/watch?v=F_hjaeJ07ro#t=366

**Comment by jaswsinc** [comment]
Thanks. I was able to reproduce this at zencache.com, so it might be a conflict with another plugin there. Taking a closer look.

**Comment by jaswsinc** [comment]
@raamdev This should be resolved now. I'll let you close this out once you have confirmed :-)

~ To confirm, please Trash and then Permanently Delete the problem post. Then wait a few minutes for it to be pulled back in from GitHub, and confirm that `>` is now preserved as it should be.

**Comment by raamdev** [comment]
Confirmed fixed! Thank you!

![2015-01-16_11-40-35](https://cloud.githubusercontent.com/assets/53005/5779902/9434614c-9d74-11e4-848c-b16071057e3d.png)
