### ISSUE TITLE
Navigation Tabs and KB Article Footer layouts are broken on mobile devices

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#34]
The following screenshots are from an iPhone 5 (resolution 568 x 320):

![img_4582](https://cloud.githubusercontent.com/assets/53005/5782278/c6633f18-9d87-11e4-9675-8acbe87711fd.PNG)
![img_4584](https://cloud.githubusercontent.com/assets/53005/5782279/c663e4fe-9d87-11e4-85f9-888f19030042.PNG)

And portrait mode:

![img_4586](https://cloud.githubusercontent.com/assets/53005/5782276/c66073b4-9d87-11e4-9418-d871dddf5833.PNG)
![img_4585](https://cloud.githubusercontent.com/assets/53005/5782277/c66246da-9d87-11e4-934d-f84dccd1f1ef.PNG)

**Comment by jaswsinc** [comment]
Thanks for the screenshot! I meant to fork an issue for this and forgot to do it.

**Comment by jaswsinc** [comment]
WPKBA is now fully responsive across all front-end components.

@raamdev I'll let you close this once you can confirm. You're better at testing this than I am, so if you see any remaining issues please let me know. Thanks again!

**Comment by raamdev** [comment]
> WPKBA is now fully responsive across all front-end components.

Woohoo! Totally awesome! :dancer: 

# iPhone 5

## Portrait

![img_4594](https://cloud.githubusercontent.com/assets/53005/5806343/8cdc7956-9fe6-11e4-9abb-5ad7bcf46f41.PNG)
![img_4593](https://cloud.githubusercontent.com/assets/53005/5806344/8ce06200-9fe6-11e4-9243-822ab4643568.PNG)

## Landscape

![img_4596](https://cloud.githubusercontent.com/assets/53005/5806348/8f1626b8-9fe6-11e4-89e1-b0d5b64444e2.PNG)
![img_4595](https://cloud.githubusercontent.com/assets/53005/5806349/8f1a641c-9fe6-11e4-9ed0-0ee6b15ffc2b.PNG)


# iPad Air

## Portrait

![img_2175](https://cloud.githubusercontent.com/assets/53005/5806354/96faa91c-9fe6-11e4-869f-7470ab3fe35c.PNG)
![img_2174](https://cloud.githubusercontent.com/assets/53005/5806353/96fa39fa-9fe6-11e4-8825-0931dc2bfaeb.PNG)

## Landscape

![img_2173](https://cloud.githubusercontent.com/assets/53005/5806356/99629a84-9fe6-11e4-86f7-c68e6eb095c3.PNG)
![img_2172](https://cloud.githubusercontent.com/assets/53005/5806357/99643646-9fe6-11e4-98ca-5a0b93d00688.PNG)

**Comment by jaswsinc** [comment]
Thank you so much for those screenshots. Super helpful!
