### ISSUE TITLE
Enhance Search Functionality

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#36]
A fork of https://github.com/websharks/wp-kb-articles/issues/29

Forking a separate issue so that we can continue to work at improving search functionality in WP KB Pro. Improving search functionality for users looking through KB articles is something that is likely to be an ongoing concern.

- [ ] Improve search result priorities; i.e. after the initial sorting by popularity, comment counts, dates, etc; we should also look at giving a higher priority to results that include keywords in the title, and a higher priority should be given to results that have tags, as opposed to matches on the content body only.

- [ ] Investigate what might be coming in future versions of WordPress. No part of WordPress supports MySQL fulltext indexes yet, which is really the underlying cause of the weak search functionality in the WP core. While working on Comment Mail, for instance, I went with custom DB tables that _do_ support fulltext indexes. In the case of custom post types, those are in the core DB. A little more difficult to search without having fulltext indexes.

  I have seen a few plugins that actually add fulltext indexes to the WP core tables to overcome this.

**Comment by raamdev** [comment]
@jaswsinc writes (in 2015-01-27 team meeting)...
> This issue is dead I think. I researched this and it seems not doable. 
> Changing the sort order of a custom post type in ways that go beyond what the WP DB is capable of seems too difficult, and perhaps not possible.

@raamdev writes...
> I agree it's probably worth scrapping that issue for now. If we discover there's a very high demand for better search, we'd need to rewrite the plugin to use custom DB tables so that we can add whatever functionality we want.

Improved search goal related to #54.
