### ISSUE TITLE
ZenCache Compat. w/ AJAX

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#37]
It would be nice to add support for ZenCache to the AJAX implementation; i.e. making it easy for ZenCache to cache the AJAX requests. Reduce overhead and improve speed.

The only reason these are not cached at present, is that the AJAX queries are submitting GET requests. We could look at ways to tell ZenCache that it's OK to cache these. e.g. `?zcAC=1&zcABC=1`.

**Comment by jaswsinc** [comment]
This has been implemented. Related in part to: websharks/quick-cache#401

**Comment by raamdev** [comment]
Woohoo!
