### ISSUE TITLE
Show a "Clear Filter" button when filtering by tags

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#38]
When the article list is being filtered by one or more tags, it's impossible to know that a filter is being applied without first opening the "Filter by Tag" dropdown box.

For example, this view is being filtered by a tag, but you have no indication of that:

![2015-01-16_22-35-30](https://cloud.githubusercontent.com/assets/53005/5787535/7275b55e-9dd0-11e4-8944-c50fa7ef751d.png)

Additionally, if I _think_ some kind of filter is being applied, my instinctive reaction is to click on the selected category again (in this case, "Questions") in attempt to "clear" any filter that might be applied and just see a list of all "Questions". 

However, clicking "Questions" does not do anything.

The only way I can clear the filter is to go into "Filter by Tag", click on the selected tags to unselect them, and then click the "Filter by Tags" button. That just feels _very_ unintuitive. (I have to click "Filter by Tags" to _remove_ the filter?)

![2015-01-16_22-35-43](https://cloud.githubusercontent.com/assets/53005/5787540/d44015e0-9dd0-11e4-8d00-e22826186f98.png)

# How this can be fixed

If we simply added a note with a "clear" button whenever the view was being filtered by tags, that would solve this issue nicely:

![2015-01-16_22-45-22](https://cloud.githubusercontent.com/assets/53005/5787557/6f2f813a-9dd1-11e4-9838-b5fe5340614b.png)

**Comment by raamdev** [comment]
In fact, you could even replace the Search field with that message whenever the view is being filtered by Tag, i.e., make the search field only visible when no filter is being applied. That would save some space on the UI. It also makes sense, as filtering by tag is a type of "search", so replacing the Search box with a message about the view currently being filtered would make sense.

**Comment by raamdev** [comment]
Related to #39.

**Comment by jaswsinc** [comment]
There have been several improvements to the styles and functionality associated with the Filter by Tag functionality and the other filters that one can apply while navigating the list and/or via URL formulations. I'm going to leave this open for now and let you close it after you've had some time to inspect the latest.

I updated zencache.com with the latest dev branch.

![2015-01-19_02-47-19](https://cloud.githubusercontent.com/assets/1563559/5800069/a1f51a42-9f86-11e4-8a5f-4f976ac6bcb4.png)

**Comment by raamdev** [comment]
I played around with the new functionality a bit and it's fantastic. Great job implementing this! 

_Aside: At first I was concerned with how category filters are additive to other filters (i.e., you can filter by Category and Tag/Author/etc), but I realized after using the new interface for a bit that it makes total sense and it's not unintuitive. It especially makes sense if you consider that a common workflow when visiting the KB will likely be `Tag → Category` or `Category → Tag`._

Anyway, I just wanted to share that aside. I think the implementation is fantastic and I wouldn't change a thing!

**Comment by jaswsinc** [comment]
Awesome! Thanks for testing this for me.
