### ISSUE TITLE
Show "Clear" button when showing Search Results

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#39]
Related to #38.

When using the Search box to conduct a search, it's not intuitive how I can "clear" my search.

![2015-01-16_22-52-36](https://cloud.githubusercontent.com/assets/53005/5787582/74dc49c8-9dd2-11e4-90ab-4bc960b3d34c.png)

If there was a simple "Clear Search" button that appeared next to the search field whenever the interface was displaying search results, that would make things much more intuitive.

![2015-01-16_22-56-16](https://cloud.githubusercontent.com/assets/53005/5787592/e659802a-9dd2-11e4-9de9-3fc8afcefdd8.png)

**Comment by jaswsinc** [comment]
Agreed. I also think there should be a visual that goes along with some of the filters applied when clicking on an author's name for instance, or on a specific tag. It's obvious when you use "Filter By Tag", but clicking on the author name or on a specific tag doesn't show the user what has actually occurred with the list.

**Comment by raamdev** [comment]
> there should be a visual that goes along with some of the filters applied when clicking on an author's name for instance, or on a specific tag.

I see what you mean. Perhaps we can make the current filter information and the clear button a little more prominent then, something like this:

![2015-01-17_18-45-17](https://cloud.githubusercontent.com/assets/53005/5790829/26e828f2-9e79-11e4-83ee-c63a0054a328.png)

**Comment by jaswsinc** [comment]
Agreed.

**Comment by jaswsinc** [comment]
Related to #38

**Comment by jaswsinc** [comment]
I have a reference to the details discussed here, but I'm going to close this issue in favor of #38. Thanks for the help!
