### ISSUE TITLE
Configuration Option to Disable WP KB Article editor when GitHub Integration is Enabled

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#41]
Referencing: https://github.com/websharks/wp-kb-articles-kb/issues/2

When GitHub Integration is enabled, modifications to KB Articles inside WordPress may be overwritten the next time the associated Markdown file on GitHub is changed, unless those changes are manually mirrored between WordPress and the Markdown file.

To avoid accidental loss, I recommend we add an option to the WP KB Articles plugin to disabling the post Editor for WP KB Articles when GitHub Integration is enabled.

**Comment by jaswsinc** [comment]
This has been implemented and the option is enabled by default when GH integration is configured and enabled with WPKBA.
![2015-01-19_02-51-02](https://cloud.githubusercontent.com/assets/1563559/5800030/15907ccc-9f86-11e4-9e67-c4ad4636c02b.png)

**Comment by raamdev** [comment]
Woohooo! So awesome! Thank you.
