### ISSUE TITLE
Save changes to Markdown files for Published KB Articles as Pending Revisions

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#44]
@raamdev writes...
> When a Markdown file is updated for a KB Article that has been set to Published in WordPress, what happens to the state of the KB Article on the WordPress side when the plugin detects and imports the changed Markdown file in the GitHub Repo? Does the KB Article get updated and remain Published, or does it go back to the Pending state?

@jaswsinc writes...
> It is updated and remains published. Unless, the  `status:` is set to something else in the YAML.

@raamdev writes... 
> Hmm. I wonder if it would be a good idea to have an option to change that behavior in the plugin config. I think it would be very helpful if changes reverted the status of the article to Pending, so that it can be re-reviewed (as it has been changed, possibly by someone who is not the Project Lead; the Project Lead may want to review all changes before they are seen live).

@jaswsinc writes...
> Yep. I'm not sure what would be best. One problem with changing it to Pending is that it takes the article offline in an automated way.

@raamdev writes...
> Yeah, but I feel that's better than having changes to the GitHub Repo reflected on the live site in an automated way... I mean, doing it that way makes the assumption that anyone who can commit to the KB GitHub Repo should have permission to update and publish articles on the live site.
> 
> Actually, I think that's fine. If someone wanted to restrict this, they could simply require that people submit Pull Requests to the KB GitHub Repo, and only accepted Pull Requests (or only Pull Requests that were merged to a specific branch) will actually get pulled in by the WP KB Articles GitHub Processor.

@jaswsinc writes...
> I wonder if there is a way to create a Pending revision. WordPress does support revisions, but I'm not sure if they'd work for something like this. In my mind, a new Pending revision on the WordPress (maybe as an configurable option) would be nice.

---

Referencing a (slightly old) plugin that appears to accomplish Pending Revisions: https://wordpress.org/plugins/revisionary/

**Comment by jaswsinc** [comment]
@raamdev writes...
> Actually, I think that's fine. If someone wanted to restrict this, they could simply require that people submit Pull Requests to the KB GitHub Repo, and only accepted Pull Requests (or only Pull Requests that were merged to a specific branch) will actually get pulled in by the WP KB Articles GitHub Processor.

Exactly.

After thinking about this some more, I agree with what you said here and I'm inclined to close this issue. Do you see any reason to keep this open?

**Aside:** This is yet another reason why I wish GitHub would support branch-specific permissions like BitBucket does. You could then work on a separate branch of a KB repo and that would not impact the branch that is associated with the live site.

**Comment by raamdev** [comment]
> Do you see any reason to keep this open?

Nope. I'd say this can be closed.



> Aside: This is yet another reason why I wish GitHub would support branch-specific permissions like BitBucket does. You could then have a team work on a separate branch of a KB repo and that would not impact the branch that is associated with the live site.

Yeah, that's an annoying missing feature on GitHub. That said, I think most people deal with this by using the cloning functionality. Instead of giving people access to push to the main repo, let them clone the repo and then submit a Pull Request. The downside is that you can't really collaborate this way--everybody has their own clone and their own PRs and only people who have write access to the main repo can actually "collaborate".

**Comment by jaswsinc** [comment]
@raamdev writes...
> That said, I think most people deal with this by using the cloning functionality

@raamdev writes...
> Nope. I'd say this can be closed.

Copy that. Thanks :-)
