### ISSUE TITLE
Use Markdown YAML `title` Key to Generate WP KB Article Permalink

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#45]
When using the GitHub Integration, the GitHub Processor imports a Markdown file and uses the Markdown filename (e.g., `4-recommended-nginx-config.md`) to generate the WordPress permalink, prepending the article category to the filename to end up with something like `/questions-4-recommended-nginx-config/` as the final permalink.

It would be highly preferable, and the expected behavior in my opinion, to instead generate the permalink using the `title:` value in the YAML config. This would mirror the way WordPress generates permalinks based on whatever you enter in the Title field when creating a new Post.

For example, for the article with a title of `What is the recommended Nginx Configuration?`, I was expecting to see a permalink of `/what-is-the-recommended-nginx-configuration/`. Or, if you wanted to include the category to help make each permalink extra unique, `/questions-what-is-the-recommended-nginx-configuration/` would be fine too.

If the YAML config doesn't contain a `title:` key, I'd say the current behavior (generating the permalink using the filename) is a perfect fallback.

**Comment by jaswsinc** [comment]
Agreed. Marking this as ready for work.

**Comment by jaswsinc** [comment]
This has been implemented.

**Comment by raamdev** [comment]
Woohoo! Confirmed working:

```
http://zencache.com/kb-article/what-is-the-recommended-nginx-configuration/
http://zencache.com/kb-article/why-am-i-getting-a-404-error-when-running-the-pro-updater/
http://zencache.com/kb-article/what-are-u-directories-e-g-category-u/
```
