### ISSUE TITLE
Add link to GitHub Integration options in read-only editor message

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#47]
When GitHub Integration is active and the KB Article editor is read-only, it would be good to link to the GitHub Integration options that is causing the editor to be read-only. We should keep in mind that not everyone who views these KB Articles on the WordPress side will even be familiar with the WP KB Articles plugin.

I suggest modifying the read-only message to include a link like this: 

![2015-01-19_14-35-21](https://cloud.githubusercontent.com/assets/53005/5806637/efa02f7c-9fe8-11e4-8fa7-712aa4ced3d8.png)
![2015-01-19_14-36-26](https://cloud.githubusercontent.com/assets/53005/5806638/f0fbbfda-9fe8-11e4-8f63-48206aabf4c8.png)

Related to #41.

**Comment by jaswsinc** [comment]
Agree. Thank you. Marking this as ready for work.
