### ISSUE TITLE
Move Popularity icon on Articles List to end of post meta

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#48]
When you scan an articles list, such as this one, observe where your eyes feel pulled:

![2015-01-19_15-22-04](https://cloud.githubusercontent.com/assets/53005/5807329/25ca58a0-9ff0-11e4-9ccb-97eb5d572411.png)

Color always attracts out attention, _especially_ red, so even when our intention is to scan the article titles, our eyes subconsciously want us to look at the red hearts. That makes us spend less time scanning each title, as resisting that urge to look at the red heart makes us uncomfortable when reading longer titles:

![2015-01-19_15-17-13](https://cloud.githubusercontent.com/assets/53005/5807345/5d6dd8ae-9ff0-11e4-9a64-29cd8d407033.png)

If we move the red popularity hearts to the end of the post meta lines (instead of the beginning) that will result in less stress on scanning/reading longer article titles and better overall flow:

![2015-01-19_15-27-43](https://cloud.githubusercontent.com/assets/53005/5807357/91810a4e-9ff0-11e4-8ddd-f4ddf30eb572.png)

**Comment by jaswsinc** [comment]
Thanks for the screenshots! Marking this as ready for work.
