### ISSUE TITLE
UI Shortcodes / Clone of Digital Ocean

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#5]
We need to build a set of shortcodes that will create a clone of the Digital Ocean UI for KB articles, which is a feature requested by others on the team. See: https://www.digitalocean.com/community/

~~- [ ] **Featured Categories Shortcode** to include a display of featured/parent categories.~~
 
![2014-12-22_17-03-05](https://cloud.githubusercontent.com/assets/1563559/5533799/6d364406-89fc-11e4-9939-8e599a0fe270.png)

- [x] **Tags Shortcode** to include a list of all tags. This will also be used by the List Shortcode a part of the drop down functionality needed to create a clone. ~~What Digital Oceans calls "Tags" we will create as Categories in the WordPress database.~~

![2014-12-22_17-04-00](https://cloud.githubusercontent.com/assets/1563559/5533809/c1d0a074-89fc-11e4-84b4-ceff01cb933a.png)

- [x] **List Shortcode** to include a paginated list of all KB articles. This shortcode will need to include _many_ configurable attributes eventually. For now, we can work to implement the list with defaults that create a clone of the Digital Ocean KB. In the future this shortcode should become more powerful.

![2014-12-22_17-06-36](https://cloud.githubusercontent.com/assets/1563559/5533819/21459f82-89fd-11e4-9008-34008fe781df.png)

- [ ] **Search Box Shortcode** To provide a search box capable of searching all KB articles; where a **List Shortcode** has been presented and will be filtered by any search that takes place.

![2014-12-22_17-08-47](https://cloud.githubusercontent.com/assets/1563559/5533824/4c8cd66a-89fd-11e4-82b2-59704b125591.png)

---

- [ ] Make all of the above responsive.
- [x] Add templates for the output of any shortcodes.

**Comment by brucewsinc** [comment]
I'd love to see any screenshots you have of this in s2Clean.

**Comment by jaswsinc** [comment]
Screenshots:

![2015-01-12_09-16-32](https://cloud.githubusercontent.com/assets/1563559/5708242/d8118ea8-9a3b-11e4-9d60-abf092c4e149.png)
![2015-01-12_09-16-48](https://cloud.githubusercontent.com/assets/1563559/5708243/d8181d54-9a3b-11e4-874a-7e760a0aee8b.png)

**Comment by brucewsinc** [comment]
Sweet! I'm excited to see this in action!

**Comment by raamdev** [comment]
Wow, super cool!
