### ISSUE TITLE
Feature Request: Specify GitHub Processor Interval

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#52]
It would be nice to allow the site owner to configure how frequently the GitHub Processor runs.

Related: #51

**Comment by jaswsinc** [comment]
Agreed. Marking this as ready for work.

**Comment by jaswsinc** [comment]
I can see that this specific feature is not going to be possible, for a few reasons. The GitHub Processor needs to remain on a fixed timeframe in order for the engine to work in the most optimized way possible. Not just for sub-tree navigation, but for the limitations imposed by the GitHub API, and for rate limits also.

However, there are some important options associated with this behavior that would allow for more control over this, and those could be exposed in the UI at some point in the future. Referencing: https://github.com/websharks/wp-kb-articles-pro/blob/000000-dev/wp-kb-articles-pro/plugin.inc.php#L415

**Comment by raamdev** [comment]
> However, there are some important options associated with this behavior that would allow for more control over this, and those could be exposed in the UI at some point in the future. Referencing: https://github.com/websharks/wp-kb-articles-pro/blob/000000-dev/wp-kb-articles-pro/plugin.inc.php#L415

I wouldn't even bother with exposing those. If anything, we could add filters so an advanced site-owner could override the defaults if they _really_ wanted to, but I'm not seeing those as something we'd want to clutter the UI with.

I'd say we can call this issue closed. The work you did adding the GitHub Processor Button and the "Sync w/ GitHub" links on each KB Article are sufficient to provide additional control over this functionality, IMO.

@jaswsinc I'll let you close this issue if you concur. :-)

**Comment by jaswsinc** [comment]
Agreed :-)
