### ISSUE TITLE
Use shortlinks for all links in inline documentation

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#53]
Before the plugin is released, we should make sure that we update all links in the inline documentation to use shortlinks that can easily be updated in case the target URL changes. This will avoid the chances of breaking links in software that's in the wild.

We can probably setup WP-Redirects on the WP KB Articles website for this.

For example, here are some links that should be updated to use shortlinks that redirect to the real link:

![2015-01-19_21-19-20](https://cloud.githubusercontent.com/assets/53005/5811266/110b5478-a022-11e4-8c1d-f1bf51752f5d.png)

**Comment by jaswsinc** [comment]
Agree! Marking this as "on hold" for now until the site is up and running.
