### ISSUE TITLE
Feature Request: "Trending" and "Popular" Navigation Tabs

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#54]
When the KB grows to the point where there are hundreds (or thousands) of KB Articles, I foresee "Trending" and "Popular" tabs being extremely useful to newcomers.

![2015-01-21_20-05-28](https://cloud.githubusercontent.com/assets/53005/5848733/dcafedae-a1a9-11e4-9233-b7129ab75c51.png)

### Why the "Trending" tab would be useful

The "Trending" tab would show KB Articles that have had the most views in the past 24 hours (configurable). 

This would be useful if, for example, an 3rd-party API changes and causes a software feature to start reporting an error. We'd create a KB Article to address this error and if that specific KB Article received lots of hits in the past 24 hours, it would show high on the "Trending" list. If a new visitor comes along because they experienced that same error, they could check the "Trending" tab to see if its a 'hot topic' and quickly locate the solution. 

Without a "Trending" list in this scenario, the visitor would need to do a search, and hope that the results return what they're looking for.

### Why the "Popular" tab would be useful

The "Popular" tab would show KB articles that have had the most number of "Hearts" (favorites).

This would be useful if, for example, lots of people over time have found a specific KB Article (e.g., tutorial, question, or video) useful. Over time, that KB Article would gather a large number of Hearts, which we could use to rank it on the Popular list. 

If we were also tracking "views" to a specific KB Article (required for a "Trending" tab), we could combine Visits with Hearts to build an even more accurate "Popular" list.

### Data that's currently missing

We already track popularity using the "hearts" feature. What's missing to build a "Trending" list, and to further enhance the "Popular" list, would be data on "views". This could be a simple incrementing value attached to each KB Article that is incremented any time the article is viewed.

**Comment by jaswsinc** [comment]
Agree. Sounds like a plan to me. I'd call this ready to work on.

**Comment by jaswsinc** [comment]
This has been implemented as a pro feature.

- Stats now collected in a DB table of their own. We keep daily views (hits) and also a more accurate count of unique visitors to each KB article on a daily basis. We could eventually build historical graphs out of this data too; i.e. another pro feature.
- Trending category support.
- Popular category support.

This can be implemented by adding `tab_categories="trending,popular"` to the shortcode; or in addition to any other categories that you are already displaying as tabs.

- The Trending category view shows highest traffic articles in the last seven days. Ordered by total visits over last 7 days DESC, popularity (hearts) DESC, comment count DESC, date DESC.

   _The number of days in the trending calculation can be altered with shortcode attribute `trending_days="7"`. This can be anything >= `1`._

- The Popular category view shows overall most popular articles. Ordered by popularity (hearts) DESC, total lifetime visits DESC, comment count DESC, date DESC.

**Comment by raamdev** [comment]
Woohooo! Thank you! 

I'm going to write a WP KB Articles KB Article today covering how to use this.
