### ISSUE TITLE
Differentiate the "Filter by Tag" Tab from Category Tabs

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#55]
Currently the "Filter by Tag" tab looks no different than the Category tabs:

![2015-01-21_20-27-02](https://cloud.githubusercontent.com/assets/53005/5848921/2de66c0a-a1ac-11e4-9097-451d2866308a.png)

Since "Filtering by Tag" is the primary way of filtering the KB Articles, I suggest that we differentiate this a bit by changing its color (you'll notice the [Digital Ocean Community interface](https://www.digitalocean.com/community/questions?primary_filter=popular) does this). Here's the tab with a background color of `#FDFDFD`:

![2015-01-21_20-27-44](https://cloud.githubusercontent.com/assets/53005/5848935/61d6da54-a1ac-11e4-9955-806f93123343.png)

It's a subtle change, but it goes a long way to indicating that the tab is special and that it _does_ something.

**Comment by jaswsinc** [comment]
Agreed.
