### ISSUE TITLE
Escape Shortcodes

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#62]
WPKBA needs to automatically escape shortcodes used in the body of an article that is pulled from GitHub, before displaying the contents of the article on-site.

```
[[shortcode]]
```

**Comment by jaswsinc** [comment]
@jaswsinc writes...
> I believe the s2Clean theme might actually not be a problem in this regard, because backticks (pre/code tags) are pulled out and tokenized by the MD parser in s2Clean. Still, we should properly escape shortcodes I think, that way WPKBA will be more compatible with a variety of themes, not just with s2Clean. I'll need to confirm that s2Clean can in fact do this also. I'm not certain.

**Comment by raamdev** [comment]
> Still, we should properly escape shortcodes I think, that way WPKBA will be more compatible with a variety of themes, not just with s2Clean. I'll need to confirm that s2Clean can in fact do this also. I'm not certain.

I suggest making this an option in WP KB Articles, just in case someone's theme has issues with automatically escaping shortcodes in KB Articles and they want to turn off the automatic-escaping...
