### ISSUE TITLE
Automatically convert issue link references.

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#64]
It would be nice if WPKBA could automatically convert links in an article that reference another issue in the same repo. In other words, converting links in a way that would reference the KB Article Post in the site once it is moved over into WordPress.

**Comment by raamdev** [comment]
+1! That would be awesome. Definitely a little tricky to do, but would certainly make cross-referencing KB Articles within the same repo (always a good idea!) a heck of a lot less work.

**Comment by jaswsinc** [comment]
This has been implemented. Here is a diagram to help explain how this works. This functionality is enabled automatically when you start using the `github-issue:` key in your YAML configuration.

![issue-references](https://cloud.githubusercontent.com/assets/1563559/6401742/f2626656-bdae-11e4-8055-be90de35a568.png)

**Comment by raamdev** [comment]
@jaswsinc Woohoo! Awesome.

I wonder: Would it make sense to look into adding integration between this feature and WP Redirects, i.e., if we add an external API to WP Redirects that allows for creating / searching for Redirects, then we could have WP KB Articles replace Issue URLs with an associated WP Redirect (that would redirect to the live KB Article).

**Comment by jaswsinc** [comment]
Sounds like a good idea to me. If WP Redirects could also be integrated with Bitly to achieve a custom domain being used together with the redirection, that would really add a lot of value to this combo; i.e., we could use that to achieve `http://wpkba.com/ee89aJk` style redirects if configured for it.

**Comment by jaswsinc** [comment]
> integrated with Bitly to achieve

Scratch that. This would prevent WP Redirects from being able to keep stats, etc.

**Comment by raamdev** [comment]
> This would prevent WP Redirects from being able to keep stats, etc.

True, but it would also allow for collecting a lot _more_ stats, since Bitly tracks things like how many clicks from Twitter, Facebook, Google+, etc. I've opened a feature request to add Bitly support to WP Redirects; if you have further thoughts on this, please share them over there: https://github.com/websharks/wp-redirects/issues/30
