### ISSUE TITLE
[toc] Placeholder for Table of Contents

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#68]
A fork of https://github.com/websharks/zencache.com/issues/29#issuecomment-74444556

If the article contains `[toc]` we put it there. If not, it goes into a default location.

**Comment by jaswsinc** [comment]
Giving this `3` story points.

**Comment by jaswsinc** [comment]
@raamdev This is now possible. However, I chose to use `%%toc%%` instead of `[toc]` to avoid shortcode conflicts. ZenCache.com has been updated to support this.

**Comment by raamdev** [comment]
@jaswsinc Cool! Thank you. We'll make use of this when we take care of https://github.com/websharks/zencache.com/issues/33.
