### ISSUE TITLE
Search Box Shortcode

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#69]
The objective here is to improve the look n' feel of the KB articles list by repositioning and restyling the search box.

Ideally, we could introduce a new shortcode that is specifically for the search box so that a site owner can choose where it goes and/or integrate a search box into places where the list itself might not be shown.

@raamdev writes...
> If I was going to move the search box, I would move it up, not down. If you check out https://www.digitalocean.com/community/ you'll notice they also have their search box up top.

> Also, while we're talking about the search box, I the inner padding feels a bit off to me, like it needs some more room in there. And also, the dark grey background (when inactive) feels a bit _too_ dark... something lighter, almost white, would be great.

**Comment by jaswsinc** [comment]
A new shortcode has been added: `[kb_articles_list_search_box /]`.

Implemented at ZenCache.com and s2Member.com

![2015-02-20_23-05-16](https://cloud.githubusercontent.com/assets/1563559/6313404/0649850e-b955-11e4-8836-bf5bc59e1869.png)

**Comment by raamdev** [comment]
Woohoo! Looks great!

**Comment by jaswsinc** [comment]
Thank you :-)

I forgot to add that this shortcode accepts two attributes.

- `q=""` Prefill the search box with a specific query (optional).
- `action=""` The `<form action="">` URL; i.e., the page hosting `[kb_articles_list /]`. Defaults to the current page. This attribute is also optional.

**Comment by raamdev** [comment]
@jaswsinc Will the plugin UI be updated to include this documentation or should a KB Article be written?

**Comment by jaswsinc** [comment]
My vote would be for a KB article. Whenever I document it in the Dashboard we can reference the article so that more information can be provided and updated over time. I have not documented either of the WPKBA shortcodes yet, sorry.

**Comment by raamdev** [comment]
@jaswsinc Copy that. I'll add that to my `todo` list. :-)
