### ISSUE TITLE
First item in TOC links to top of video when article starts with a video

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#77]
If a KB Article starts with a video (such as [this one](http://zencache.com/kb-article/how-to-migrate-from-quick-cache-pro-to-zencache-pro/)) and is followed by an H1 tag, the link to that first header item in the Table of Contents moves the browser window to the top of the video, instead of moving to the top of the header item.

This has been confirmed on Chrome and Safari, but seems to work fine in Firefox (so likely a WebKit issue).

![2015-03-02_18-45-00](https://cloud.githubusercontent.com/assets/53005/6453481/69626b74-c10c-11e4-8b82-5efcf46735dc.png)

**Comment by jaswsinc** [comment]
`display:block` seems to correct the problem. Can you confirm?

![2015-03-03_14-14-29](https://cloud.githubusercontent.com/assets/1563559/6474710/bf71b698-c1af-11e4-8a31-06522cc9d4fa.png)

**Comment by jaswsinc** [comment]
This was fixed in the last round of updates.

**Comment by raamdev** [comment]
> Can you confirm?

Confirmed. It works great now in Safari and Google Chrome.
