### ISSUE TITLE
UI Shortcodes / A Little Love

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#8]
Eventually it would be nice for WP KB Articles to support a user rating/score based on reader approval. Like Digital Ocean, this should impact the ranking of search results and other list views also.

![2014-12-22_17-28-36](https://cloud.githubusercontent.com/assets/1563559/5533943/40c7a29e-8a00-11e4-986e-2e2533a2cdf5.png)

![2014-12-22_17-30-51](https://cloud.githubusercontent.com/assets/1563559/5533948/4ddab96c-8a00-11e4-9549-571aa89e04fe.png)

![2014-12-22_17-31-16](https://cloud.githubusercontent.com/assets/1563559/5533951/600501ce-8a00-11e4-96cb-cbf8a7fd2688.png)

**Comment by jaswsinc** [comment]
Implemented while working on #5

**Comment by jaswsinc** [comment]
Screenshots.

![2015-01-12_09-12-02](https://cloud.githubusercontent.com/assets/1563559/5708152/2c8dafc6-9a3b-11e4-9179-58a4696dd508.png)
![2015-01-12_09-12-29](https://cloud.githubusercontent.com/assets/1563559/5708153/2ca6ff8a-9a3b-11e4-9520-ec28c75e31d1.png)

**Comment by brucewsinc** [comment]
Awesome!

**Comment by raamdev** [comment]
Woohoo!
