### ISSUE TITLE
Unable to use <?php ?> tags in KB Articles

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#81]
I noticed that when I add the following code to a Markdown file (see [31-disable-cache-locking.md](https://github.com/websharks/zencache-kb/blob/master/questions/31-disable-cache-locking.md)):

```
<?php
if(!defined('WPINC')) // MUST have WordPress.
    exit('Do NOT access this file directly: '.basename(__FILE__));

function disable_cache_locking() 
{
    $ac = $GLOBALS['zencache__advanced_cache']; // See: `advanced-cache.php`.
    $ac->add_filter('zencache\\share_disable_cache_locking', function(){ return TRUE; });
}

disable_cache_locking(); // Run this plugin.
?>
```

The KB Article (see [How do I disable cache locking?](https://zencache.com/wp-admin/post.php?post=1039&action=edit)) shows up like this when it gets imported into WordPress via the WP KB Articles GitHub Processor:

![2015-03-10_17-40-29](https://cloud.githubusercontent.com/assets/53005/6586021/972e05d6-c74c-11e4-9e68-9bde22a4906a.png)

As you can see, a whole section at the top is getting cut off.

I tried changing the PHP tags to `<!php !>` in the Markdown file and while that worked (the full code was shown in WordPress after being imported) the tags themselves show as `<!php !>` when viewing the KB Article. 

I tried using `&gt;` and `&lt;` but that did not help, as the entities themselves showed up in the code box when viewing the KB Article.

**Comment by jaswsinc** [comment]
Can you try removing the backticks from this line in the code sample and see if that serves as a workaround?

	// See: `advanced-cache.php`.

My thinking is that these embedded backticks are causing a problem with the s2Clean parser.

**Comment by jaswsinc** [comment]
> My thinking is that these embedded backticks are causing a problem with the s2Clean parser.

↑ Scratch that. Leaving off the closing `?>` tag does the trick though.  Not sure why yet. Looking into it though. Thanks for the report.

**Comment by jaswsinc** [comment]
**Aside:** Nothing to do with the bug here, but I have found that when posting MU plugin files and hacks like this, it is best to exclude the closing `?>` tag altogether. It is unnecessary.

However, the real reason I exclude this in code samples, is that if we include it, and a novice attempts to implement a hack file where it includes a close PHP tag `?>`, plus extra whitespace after, this will introduce whitespace into the output buffer inadvertently. Most novice site owners don't realize the issue.

For instance, if I post the following code sample:

```php
<?php
add_filter('foo', function(){ bar(); });
?>
```

And somebody comes along and creates a file that actually contains:

```php
<?php
add_filter('foo', function(){ bar(); });
?>
 
```

There is now a blank line after the `?>` tag, which will cause an error on their WordPress installation; i.e., in the form of an MU plugin file, this runs before headers are sent. Introducing output of any kind will prevent headers from being sent as expected, and could corrupt cache files even.

---

Posting a code sample like this will avoid the issue altogether; i.e., there is no closing tag, and thus the file does not leave PHP mode and introduce any output whatsoever, even if there is trailing whitespace.

```php
<?php
add_filter('foo', function(){ bar(); });
```

**Comment by raamdev** [comment]
> Posting a code sample like this will avoid the issue altogether; i.e., there is no closing tag

Thanks for reinforcing why that's important. I knew it was best-practice but I forgot why and I always added the closing `?>` because many novice site owners have seen the "missing" closing bracket and told me that I have an error in my code. :-) So I've been adding it as a way to avoid people bugging me about that and me needing to explain that no, it's perfectly fine to leave off the closing bracket. 

Now that I see why it's important to leave it out (a reason that is more important than someone just "thinking" there's a bug in the code), I'll be sure to leave it off going forward. :-)

**Comment by jaswsinc** [comment]
> So I've been adding it as a way to avoid people bugging me about that and me needing to explain that no, it's perfectly fine to leave off the closing bracket.

Ah, yep. I can see that being a problem too.

**Comment by jaswsinc** [comment]
> The KB Article (see How do I disable cache locking?) shows up like this when it gets imported into WordPress via the WP KB Articles GitHub Processor:

This appears to be a bug in the Markdown Extra library. However, it does not exist in the Dingus at this time. I'm guessing the bug was fixed in a later release. Taking a closer look. Referencing: https://michelf.ca/projects/php-markdown/dingus/

**Comment by jaswsinc** [comment]
Markdown Extra is used in the s2Clean theme. WP KB Articles uses Parsedown; a lighter/simpler alternative. I'm taking a look at the possibility of updating s2Clean to Parsedown.

**Comment by jaswsinc** [comment]
Referencing: http://parsedown.org/extra/

**Comment by jaswsinc** [comment]
This was resolved by the following changes:

- Updated WPKBA to latest release of Parsedown.
- Adding support in WPKBA for Parsedown Extra.

---

Updating s2Clean theme. Switching from PHP Markdown Extra to Parsedown Extra submodules. I'm going to experiment with these changes some more over the next few days before I update ZenCache.com with these improvements. In the mean time, excluding the `?>` tag should work as a short-term solution at ZenCache.com.

**Comment by jaswsinc** [comment]
@raamdev One thing we can do to help test the latest changes in the s2Clean theme (i.e., PHP Markdown Extra vs. Parsedown Extra), is to experiment with [this Dingus](http://parsedown.org/extra/). Once I update ZenCache.com to the latest release of s2Clean, we'll be using Parsedown Extra.

See: http://parsedown.org/extra/

**Comment by raamdev** [comment]
> I'm going to experiment with these changes some more over the next few days before I update ZenCache.com with these improvements.

Copy that.

> In the mean time, excluding the `?>` tag should work as a short-term solution at ZenCache.com.

Yep that worked. I've updated and published the article: http://zencache.com/kb-article/how-do-i-disable-cache-locking/

> One thing we can do to help test the latest changes in the s2Clean theme (i.e., PHP Markdown Extra vs. Parsedown Extra), is to experiment with this Dingus. Once I update ZenCache.com to the latest release of s2Clean, we'll be using Parsedown Extra.
> 
> See: http://parsedown.org/extra/

Copy.

**Comment by jaswsinc** [comment]
Thank you. I'm going to close this. I have tested the latest changes also and I will push them over ZenCache.com very soon; i.e., as soon as we can decide what a good time for this will be.
