### ISSUE TITLE
Feature Request: 'Edit on GitHub' link to access Markdown file from WordPress

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#82]
When using the GitHub Integration, KB Articles are only edited by changing the associated Markdown file. That means making edits to KB Articles requires finding the associated Markdown file on GitHub. Right now that process looks like this:

1. Find KB Article in WordPress
1. View or Preview KB Article in WordPress
1. Click the "improve this article" link in the footer of the article to open the associated GitHub Issue
1. Click the link to the Markdown file in the GitHub Issue
1. Edit the Markdown file

I propose that we add a new YAML Key called `markdown-file:` that can contain a link to the Markdown file itself. 

```yaml
markdown-file: https://github.com/websharks/zencache-kb/blob/master/questions/33-define-wordpress-temp-directory.md
```

Then we can create convenient links to that Markdown file when the YAML Key is present:

![2015-03-12_01-13-45](https://cloud.githubusercontent.com/assets/53005/6612567/25470328-c855-11e4-904e-f2c3e5a52d39.png)
![2015-03-12_01-11-23](https://cloud.githubusercontent.com/assets/53005/6612568/26035dde-c855-11e4-8f9a-665f8ebbb61c.png)

**Comment by jaswsinc** [comment]
Great idea. I believe we can generate the link which leads back to the file without needing a new YAML config. key. That would allow this to function for all existing articles, even if they do not contain the additional key; i.e., WPKBA already knows where the underlying file is located at GitHub.

Marking this as ready for work.

**Comment by raamdev** [comment]
> we can generate the link which leads back to the file without needing a new YAML config. key.

Even better! That's awesome! I totally forgot that all that information was already available.

**Comment by jaswsinc** [comment]
Adding this in the article footer on the front end, when the current user can edit the article. I'll leave this open so we can add it in the back end also.

![2015-03-13_22-32-29](https://cloud.githubusercontent.com/assets/1563559/6650608/ab79b38c-c9d1-11e4-8a84-3899aa506949.png)

**Comment by jaswsinc** [comment]
![2015-03-13_22-50-39](https://cloud.githubusercontent.com/assets/1563559/6650659/1016898a-c9d4-11e4-8efb-df22c9de9b50.png)

![2015-03-13_22-55-45](https://cloud.githubusercontent.com/assets/1563559/6650662/203f478e-c9d4-11e4-88be-54defc4be07e.png)

**Comment by jaswsinc** [comment]
This is now shown in three places, as seen in the above screenshots.

**Comment by raamdev** [comment]
Beauuuutiful! Thank you!
