### ISSUE TITLE
TOC Width Too Narrow

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#84]
The line-clamped TOC headings are great, but there are not enough words to really give them meaning in many cases. We want line-clamping there to keep things uniform/symmetrical, but too few words in each line is just annoying. If there were a few more words presented, then a reader could gain a little more information in nearly all cases—making it easier to scan through the TOC quickly.

The current width is `20%`.

![2015-03-13_17-17-23](https://cloud.githubusercontent.com/assets/1563559/6649664/67c01f2c-c9a5-11e4-9723-bb7c696d882e.png)

I propose that this is changed to a default of `30%` and then a site owner can adjust it through the template file if they need to do so.

![2015-03-13_17-17-36](https://cloud.githubusercontent.com/assets/1563559/6649667/6dd508b4-c9a5-11e4-86eb-03804288fa3e.png)

**Comment by raamdev** [comment]
Nice! Yes, this was bugging me too. It looks much better now!
