### ISSUE TITLE
GitHub Webhook Integration / Push Events

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#85]
New feature in the latest dev branch. cc @raamdev ~ coming soon at ZenCache.com

![2015-03-13_21-33-23](https://cloud.githubusercontent.com/assets/1563559/6650493/298cd2c0-c9ca-11e4-8b5a-323deadb1864.png)

**Comment by jaswsinc** [comment]
## This makes the following possible:

- Any new articles that you add to the repo are automatically brought into WordPress instantly. For instance, if you're using the GitHub Issue to Article conversion tool, this results in the KB article instantly being imported into WordPress as pending, ready for you to approve.

- Any changes that you make on the GitHub side to an existing article, result in that article being updated on the WordPress side instantly.

## Limitations:

- This currently works only for push events that change a single file. If you clone the GitHub repo locally and push multiple commits, or a single commit to more than one file, WPKBA will ignore that event in favor of its own CRON-based processing that is more manageable for such things.

**Comment by raamdev** [comment]
@jaswsinc We need to get http://wpkbarticles.com up and running so I can start blogging about awesomeness like this!

**Comment by jaswsinc** [comment]
@raamdev writes...
> We need to get http://wpkbarticles.com up and running so I can start blogging about awesomeness like this!

Copy that :-)
