### ISSUE TITLE
GitHub Integration: Moving Markdown file results in broken link, duplicate post

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#88]
### Steps to reproduce this bug

- Create a Markdown file in `/tutorials/` and after it's pulled into WP KB Articles, mark it as Published (so it shows up on the live site).
- Move the Markdown file to `/questions/` and wait for the GitHub Processor to run (or run it manually)

### Expected Behavior

- KB Article remains in Published state and existing KB Article permalink continues to work (the KB Article itself, with its YAML config, has not changed in any way; only its physical location inside the repo)

### Observed Behavior

- The published KB Article permalink suddenly becomes inaccessible (leads to a 404 page)
- A new, duplicate KB Article shows up in the KB Articles list in the "Pending" state, with an identical permalink to the first one

---

If the first KB Article is moved to the Trash and then Permanently Deleted, and the new KB Article is set to "Published", the original KB Article permlink starts working again.

This behavior is very confusing and a site owner to decides to move KB Articles around from one directory to another in the repo will be surprised to find a bunch of duplicate KB Articles showing up in WordPress, with all the existing, previously Published and Live KB Articles now broken.

**Comment by jaswsinc** [comment]
Thanks for opening an issue about this. I forgot about it! This is what bit us on ZenCache.com during the hard launch.

**Comment by jaswsinc** [comment]
- Referencing: https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L3325
- Referencing: http://codex.wordpress.org/Function_Reference/wp_unique_post_slug

**Comment by jaswsinc** [comment]
This WP core function does not operate as I expected because WPKBA creates the post as `pending`. See this snippet.

```php
<?php
function wp_unique_post_slug( $slug, $post_ID, $post_status, $post_type, $post_parent ) {
	if ( in_array( $post_status, array( 'draft', 'pending', 'auto-draft' ) ) || ( 'inherit' == $post_status && 'revision' == $post_type ) )
		return $slug;
```

**Comment by jaswsinc** [comment]
This has been resolved. New posts created with the GitHub integration now get a default status of `pending-via-github`; i.e., a new Post Status implemented by WPKBA.

- **Note:** Changing the status via YAML to `pending` or `draft` will still cause this sort of problem, but that seems like an edge case. It is more likely that the status will be set to `publish` if it is set in the YAML.

I updated zencache.com and s2member.com after this fix was applied.

_Screenshot if from a local test installation._

![](https://www.filepicker.io/api/file/HekuDJbbSpSX9tOhOEyi#.png)

**Comment by raamdev** [comment]
Sweet! I didn't even realize a custom Post Status was an option.

> Note: Changing the status via YAML to pending or draft will still cause this sort of problem, but that seems like an edge case. It is more likely that the status will be set to publish if it is set in the YAML.

I've made a note for myself to document this quirk with the GitHub Integration in a WP KB Articles KB Article.
