### ISSUE TITLE
Automatic TOC Generation

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#9]
Eventually it would be nice if WP KB Articles could support an automatic Table of Contents generator that would be based on `<h[0-9]>` tags found in the article body.

![2014-12-22_17-32-36](https://cloud.githubusercontent.com/assets/1563559/5533978/d02e194a-8a00-11e4-8e55-5251fadb88a2.png)

**Comment by brucewsinc** [comment]
This would be something awesome to have in s2Clean, too!

**Comment by jaswsinc** [comment]
This has been implemented. I also updated the [YAML Front Matter article](https://github.com/websharks/wp-kb-articles/wiki/YAML-Front-Matter-for-GitHub-Integration) to include a new field that can be used to control this behavior (`toc-enable:`). There is also a new default config. option for this in the Dashboard with additional instructions.

cc @raamdev There's not much to this. Basically, you just add headers (either in raw HTML or with Markdown) and a TOC is generated automatically by the WPKBA plugin.

If you want to disable it globally you can do that from the Dashboard. Or, you can control it on a per-article basis (no matter what the global config. option is), by adding a YAML config. field: `toc-enable: true|false` in a specific article.

Of course, an article with no headings will already be bypassed on the TOC generation.

![2015-01-19_03-02-03](https://cloud.githubusercontent.com/assets/1563559/5800158/bdf20970-9f87-11e4-896c-d5975fe1e4ea.png)

![2015-01-19_03-04-01](https://cloud.githubusercontent.com/assets/1563559/5800173/dffcbc4a-9f87-11e4-8a32-1736a5f20193.png)

**Comment by raamdev** [comment]
Woohoo! Awesome! I love it. 

I've created a new KB Article for this: [How do I generate a Table of Contents (TOC)?](https://github.com/websharks/wp-kb-articles-kb/issues/5).
