### ISSUE TITLE
Feature Request (GitHub Integration): Link images to themselves

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#90]
When using the GitHub Integration and when writing a KB Article that includes an image like this:

```
![zencache-static-cdn-filters-diagram](https://cloud.githubusercontent.com/assets/53005/6723898/47a2d062-cdc5-11e4-8933-ed0133a9fc08.png)
```

It would be nice to have that image show up on the WordPress side in the KB Article hyperlinked to itself (i.e., linked to the file that was uploaded to WordPress by the GitHub Integration).

The reason for this is if we're showing a large image (such as the big diagram in [How do Static CDN Filters Work?](http://zencache.com/kb-article/how-do-static-cdn-filters-work/)), we'll want a way for the visitor to see the larger version of the image (if, for example, they're viewing the article from a smaller screen). 

In fact, I feel that _all_ images should be linked to themselves as a rule. I'm not seeing any reason not to do this, but we could make this an option to enable/disable this auto-linking functionality in the WP KB Articles GitHub Integration options.

---

## What Actions Need To Occur Here?

- [x] Update [this class member](https://github.com/websharks/wp-kb-articles-pro/blob/000000-dev/wp-kb-articles-pro/includes/classes/github-mirror.php#L517); adding a new body filter to deal with this.
- [x] Add a new YAML config. key that enables/disables this.
- [x] Add a new config. option in the plugin UI that sets the default value, and that default value should default to `true`.

**Comment by jaswsinc** [comment]
@raamdev writes...
> In fact, I feel that all images should be linked to themselves as a rule. I'm not seeing any reason not to do this, but we could make this an option to enable/disable this auto-linking functionality in the WP KB Articles GitHub Integration options.

Sounds perfect to me. Marking this as ready for work.

**Comment by jaswsinc** [comment]
Adding a list of actions (↑ above) that need to occur.

**Comment by jaswsinc** [comment]
This has been implemented. I'll update s2member.com and zencache.com soon.

~ I did not add options for this yet though, so I'm leaving this open for now.
