### ISSUE TITLE
Inline SVG FOUT; Wrong Color

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#95]
@raamdev writes...

> @jaswsinc: I'm not sure if you've noticed this, but I notice when I reload the WordPress Dashboard there are several icons (ZenCache, Comment Mail, and KB Articles) that show up as black for a few milliseconds before switching over to their normal color. Usually it goes by pretty quick, but it _is_ noticeable. My internet connection is unusually slow this evening so I was able to grab a screenshot this time.$0> $0> Any idea what's causing this?

Thanks. I noticed this the other day also. No idea how to correct this yet. The color for those SVG icons is supposed to be the current inherited color from the parent container.

Referencing: https://raw.githubusercontent.com/websharks/wp-kb-articles/000000-dev/wp-kb-articles/client-s/images/inline-icon.svg

I'm guessing that the FOUT effect there has something to do with Chrome's rendering of the SVG, where it picks up the body color first maybe, and then the styled menu a second later. Strange.

---

## What Actions Need To Occur Here?

- [x] Figure out why SVG graphics result in a FOUT effect.
- ~~~If we cannot, use a different approach; i.e., something other than inline SVGs.~~~

**Comment by raamdev** [comment]
I'm not too familiar with this differs (if at all) but maybe we can follow the method used by WordPress for Dashicons and create our own `@font-face` definition and then use `::before` and `content:` to load the icons on the Dashboard?

![2015-03-24_12-33-28](https://cloud.githubusercontent.com/assets/53005/6806987/394ddf14-d222-11e4-9efc-f36695e3607b.png)
![2015-03-24_12-32-49](https://cloud.githubusercontent.com/assets/53005/6806988/39fc0e04-d222-11e4-86f0-3a6217f30fed.png)

**Comment by jaswsinc** [comment]
Referencing: https://css-tricks.com/cascading-svg-fill-color/

**Comment by jaswsinc** [comment]
@raamdev writes...
> Dashicons and create our own @font-face definition and then use ::before and content: to load the icons on the Dashboard?

Sounds like a good idea to me. I'd like to see if we can figure out what the issue is with the SVGs though. That would really help me moving forward. SVGs are so awesome! I'd love to know why this is happening.

**Comment by jaswsinc** [comment]
Adding a list of actions (↑ above) that need to occur here.

**Comment by jaswsinc** [comment]
Referencing `$icon_url` in [`add_menu_page()`](https://codex.wordpress.org/Function_Reference/add_menu_page#Examples)

> (WP 3.8+) If 'data:image/svg+xml;base64...', the specified SVG data image is used as a CSS background.

**Comment by jaswsinc** [comment]
Referencing: https://github.com/WordPress/WordPress/blob/master/wp-admin/js/svg-painter.js

So WordPress is using the SVG as a background image and then recoloring it via JavaScript. That explains the FOUT. It's being recolored after it is rendered. We need to recolor it via PHP.

**Comment by jaswsinc** [comment]
This has been resolved in CM, WPKBA, and in ZenCache.

**Comment by raamdev** [comment]
> This has been resolved in CM, WPKBA, and in ZenCache.

Awesome! Nice work researching this! :+1:
