### ISSUE TITLE
Pagination navigation does not move browser to top of KB Articles list

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#97]
When I get to the bottom of a long list of KB Articles and I use the pagination navigation at the bottom to see the next page of results, I would expect it to load the next page and return me to the top of the KB Articles list.

![2015-03-25_17-34-13](https://cloud.githubusercontent.com/assets/53005/6836058/55b8c22e-d315-11e4-870b-88278f3251ba.png)

Instead what happens is the list reloads to show the next set of results, but I'm left at the bottom of the list of results and I need to manually scroll back up to the top to start going through the next list of results.

![2015-03-25_17-35-43](https://cloud.githubusercontent.com/assets/53005/6836089/885843e4-d315-11e4-9e06-96eb0b160744.png)

Clicking "Next" or using the page number navigation should always return me to the top of the list of results, as that is expected behavior.

---

## What Actions Need To Occur Here?

- [ ] We should [improve the `reload()` function here](https://github.com/websharks/wp-kb-articles/blob/000000-dev/wp-kb-articles/includes/templates/type-a/site/articles/list.js.php#L77) and [here](https://github.com/websharks/wp-kb-articles/blob/000000-dev/wp-kb-articles/includes/templates/type-s/site/articles/list.js.php#L77); and in both the lite/pro versions of the software.
- [ ] The `reload()` function should intelligently move a user back to the top of the list once the AJAX-based reload is complete.

**Comment by jaswsinc** [comment]
Thanks. Agreed.

**Comment by jaswsinc** [comment]
Adding a list of actions (↑ above) that need to occur.

**Comment by jaswsinc** [comment]
This has been resolved. s2Member.com and ZenCache.com updated.

**Comment by raamdev** [comment]
Tested and confirmed fixed. Thank you! :-)
