### ISSUE TITLE
Category Tabs Should Drop Tags

### ISSUE THREAD

**Issue by jaswsinc** [websharks/wp-kb-articles#98]
@raamdev Would you agree that clicking a Tab should clear any Tag filters?

I have noticed that clicking a Tab with filters already applied often leads me to an empty set of results. When I click a Tab, I sort of expect to see everything in that category. Do you?

![](https://www.filepicker.io/api/file/TqHD0E0dSJ5XbEn5HAyx#.png)

---

## What Actions Needs To Occur Here?

- [ ] Clicking the category tab immediately clears any tag filters, but leaves any existing search filters.
- [ ] Clicking the category tab a second time (i.e., when it already selected) should clear all other filters, including the search box; giving you everything in that category.
- [ ] Clicking the "clear" link on a search filter should also clear the search query from the search box, if it exists. See: https://github.com/websharks/wp-kb-articles/issues/99

**Comment by raamdev** [comment]
> Would you agree that clicking a Tab should clear any Tag filters?

Yes. I have noticed this quirk too--I'm not sure why I never brought it up. 

There are two ways this could be fixed:

1. Clicking the category tab immediately clears any tag filters and search filters.
1. Clicking the category tab shows that category, filtered by the applied tag and search, but clicking it a second time (e.g., clicking "Tutorials" while already viewing "Tutorials") would clear the tag and search filters.

The second option is how I would expect it to work. When I discover that my filter is still applied when switching categories, my next instinct is to click the category tab again to clear the filter.

**Comment by jaswsinc** [comment]
@raamdev writes...
> but clicking it a second time (e.g., clicking "Tutorials" while already viewing "Tutorials") would clear the tag and search filters.

Ha. Interesting. It never occurred to me that clicking it a second time would do anything different; i.e., I would not expect that myself.

**Comment by jaswsinc** [comment]
Adding a list of actions (↑ above) that need to occur.

**Comment by jaswsinc** [comment]
This has been resolved. s2Member.com and ZenCache.com updated.

**Comment by raamdev** [comment]
Tested and confirmed fixed. Thank you!
