### ISSUE TITLE
Search box missing a "clear" button

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#99]
If you use the Search box to search the KB, the search text stays there indefinitely, even if you're no longer looking at search results and you've navigated to category-specific or tag-specific results. 

The only way to "clear" the search box is to manually refresh the page (which defeats the purpose of the AJAX-nature of the entire KB) or to put your cursor in the box and manually delete the search text. Both of these make doing a new search rather annoying (you first have to do some work to clear the text for your old search). I would expect to see a little "X" icon next to the search icon that instantly clears the search text.

![2015-03-25_17-51-19](https://cloud.githubusercontent.com/assets/53005/6836419/2ba28454-d318-11e4-823e-3556a5e9bc3d.png)

---

## What Actions Need To Occur Here?

- [ ] This [template file](https://github.com/websharks/wp-kb-articles/blob/000000-dev/wp-kb-articles/includes/templates/type-a/site/articles/list-search-box.php) and [this template file](https://github.com/websharks/wp-kb-articles/blob/000000-dev/wp-kb-articles/includes/templates/type-s/site/articles/snippet/list-search-box.php) need to be updated with markup that produces an [X] icon. This needs to occur in both the lite/pro versions of the software.
- [ ] This [template file](https://github.com/websharks/wp-kb-articles/blob/000000-dev/wp-kb-articles/includes/templates/type-a/site/articles/list-search-box.js.php) and [this template file](https://github.com/websharks/wp-kb-articles/blob/000000-dev/wp-kb-articles/includes/templates/type-s/site/articles/list-search-box.js.php) need to be updated with JavaScript that handles click events on the [X] icon. This needs to occur in both the lite/pro versions of the software.
- The other suggestion to clear the search box when clicking the "clear" link can be worked on as part of [this separate issue](https://github.com/websharks/wp-kb-articles/issues/98).

**Comment by raamdev** [comment]
I would also expect the "clear" button here to clear not just the search results, but also the Search box contents itself:

![2015-03-25_17-57-38](https://cloud.githubusercontent.com/assets/53005/6836451/81acf3de-d318-11e4-9373-89a1338e3da9.png)

**Comment by raamdev** [comment]
If clicking the category tab twice is updated to clear any current filters (see https://github.com/websharks/wp-kb-articles/issues/98), that should also clear the contents of the Search box.

**Comment by raamdev** [comment]
Here's the little "X" I was thinking should be in the WP KB Articles Search box, as seen here in the Slack search box when it contains some text:

![2015-03-25_19-15-47](https://cloud.githubusercontent.com/assets/53005/6837512/717b2ffc-d323-11e4-8cbb-78ba6ab46dcd.png)

**Comment by jaswsinc** [comment]
Adding a list of actions (↑ above) that need to occur.

**Comment by jaswsinc** [comment]
This has been resolved. s2Member.com and ZenCache.com updated.

**Comment by raamdev** [comment]
Tested and confirmed fixed. Thank you!
